# Generated by Django 5.2.16 on 2026-07-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_interviewquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='generation_source',
            field=models.CharField(choices=[('AI', 'AI'), ('QUESTION_BANK', 'Question Bank')], default='AI', max_length=30),
        ),
        migrations.AddField(
            model_name='interview',
            name='prompt_version',
            field=models.CharField(default='v1', max_length=20),
        ),
        migrations.AddField(
            model_name='interview',
            name='provider',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
