# Generated by Django 5.2.16 on 2026-07-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_resume_parsed_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='parsed_data',
        ),
        migrations.AddField(
            model_name='resume',
            name='extracted_skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
