# Generated by Django 5.2.16 on 2026-07-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_remove_resume_parsed_data_resume_extracted_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='resume_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('READY', 'Ready')], default='PENDING', max_length=20),
        ),
    ]
